# Generated by Django 5.1.1 on 2024-09-27 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_on_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
